# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_revision_author_useragent'),
        ('commenting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_comments', models.IntegerField(default=0)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.DocumentID')),
            ],
        ),
    ]
