# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commenting', '0002_commentstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentstats',
            old_name='num_comments',
            new_name='count',
        ),
    ]
