# Generated by Django 2.2.4 on 2019-08-12 12:46

import db.fields
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160626_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='db.DocumentID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='revision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='+', serialize=False, to='db.Revision'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=db.fields.ManyToManyField(limit_choices_to=posts.models.limit_by_tag_contenttype, related_name='post_tagged', to='db.DocumentID'),
        ),
    ]
