# Generated by Django 2.2.4 on 2019-10-04 23:55

import db.fields
from django.db import migrations
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20190812_1246'),
        ('posts', '0003_auto_20190812_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=db.fields.ManyToManyField(limit_choices_to=images.models.limit_by_image_contenttype, related_name='post_image', to='db.DocumentID'),
        ),
    ]
