# Generated by Django 2.2.13 on 2020-10-18 18:46

import db.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20190812_1246'),
        ('posts', '0004_post_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=models.ForeignKey(limit_choices_to=db.fields.limit_by_contenttype('images.Image'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_main_image', to='db.DocumentID'),
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
