# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentid',
            name='revisions_count',
            field=models.IntegerField(default=0),
        ),
    ]
