# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20160626_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentid',
            old_name='version_created_id',
            new_name='revision_created_id',
        ),
    ]
