# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20160626_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='author_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
