# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_revision_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentid',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owns', to='db.DocumentID'),
        ),
    ]
