# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-24 22:42
from __future__ import unicode_literals

import db.privacy.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_documentid_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentid',
            name='privacy',
            field=db.privacy.field.PrivacyField(choices=[(1, 'Publico'), (2, 'Amigos'), (3, 'Privado')], default=1, verbose_name='Privacidade'),
        ),
    ]
