# Generated by Django 2.2.4 on 2019-08-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_revision_revision_document_id_and_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='type',
            field=models.CharField(choices=[('create', 'Criação'), ('change', 'Alteração'), ('delete', 'Exclusão')], max_length=6),
        ),
    ]
