# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0008_documentid_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeNode',
            fields=[
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='db.Revision')),
                ('is_tip', models.NullBooleanField()),
                ('is_deleted', models.NullBooleanField()),
                ('rank', models.IntegerField(choices=[(10, 'Kingdom'), (20, 'Phylum'), (30, 'Class'), (40, 'Order'), (50, 'Family'), (60, 'Genus'), (70, 'Species'), (80, 'Infraspecies'), (100, 'Variedade')])),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.DocumentID')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='db.DocumentID')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects_revisions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lifenode',
            unique_together=set([('is_tip', 'document')]),
        ),
    ]
