# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifenode',
            name='rank',
            field=models.IntegerField(choices=[(10, 'Kingdom'), (20, 'Phylum'), (30, 'Class'), (40, 'Order'), (50, 'Family'), (60, 'Genus'), (70, 'Species'), (80, 'Infraspecies'), (100, 'Variety')]),
        ),
    ]
