# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 21:37
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify


def forwards_func(apps, schema_editor):
    from life.models import LifeNode
    for node in LifeNode.objects.all():
        node.slug = slugify(node.title)
        node.save(update_fields=['slug'], request=None)


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0004_lifenode_slug'),
    ]

    operations = [
        migrations.RunPython(forwards_func)
    ]
