# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0005_set_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifenode',
            name='gbif_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
