# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 19:29
from __future__ import unicode_literals

import db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_description'),
        ('life', '0007_commonname_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifenode',
            name='images',
            field=db.fields.ManyToManyField(related_name='lifeNode', to='images.Image'),
        ),
    ]
