# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 20:56
from __future__ import unicode_literals

import db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0008_lifenode_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifenode',
            name='commonNames',
            field=db.fields.ManyToManyField(related_name='lifeNode_commonName', to='db.DocumentID'),
        ),
        migrations.AlterField(
            model_name='lifenode',
            name='images',
            field=db.fields.ManyToManyField(related_name='lifeNode_image', to='db.DocumentID'),
        ),
    ]
