# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_documentid_owner'),
        ('life', '0009_auto_20161116_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='db.Revision')),
                ('is_tip', models.NullBooleanField()),
                ('is_deleted', models.NullBooleanField()),
                ('value', models.CharField(max_length=512, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.DocumentID')),
                ('lifeNode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_lifeNode', to='db.DocumentID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_tag', to='db.DocumentID')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects_revisions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='characteristic',
            unique_together=set([('is_tip', 'document')]),
        ),
    ]
