# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0010_auto_20161117_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristic',
            options={'ordering': ('document_id',)},
        ),
        migrations.AlterModelOptions(
            name='commonname',
            options={'ordering': ('document_id',)},
        ),
        migrations.AlterModelOptions(
            name='lifenode',
            options={'ordering': ('document_id',)},
        ),
        migrations.AddField(
            model_name='lifenode',
            name='edibility',
            field=models.IntegerField(null=True),
        ),
    ]
