# Generated by Django 2.2.4 on 2019-10-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0012_auto_20190812_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonname',
            name='country',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='commonname',
            name='region',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
