# Generated by Django 2.2.4 on 2020-02-01 01:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0013_auto_20191003_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifenode',
            name='flower_colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('white', 'White'), ('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('pink', 'Pink'), ('pink-lilac', 'Pink Lilac'), ('lilac', 'Lilac'), ('blue', 'Blue'), ('light-blue', 'Light Blue'), ('green', 'Green'), ('purple', 'Purple'), ('black', 'Black'), ('brown', 'Brown'), ('nut-brown', 'Nut Brown'), ('wine', 'Wine'), ('cream', 'Cream')], max_length=25), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='lifenode',
            name='flower_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('simple', 'Simple'), ('dry', 'Dry'), ('dehiscent', 'Dehiscent'), ('legume', 'Legume'), ('follicle', 'Follicle'), ('capsule', 'Capsule'), ('capsule-loculicidal', 'Loculicidal Capsule'), ('capsule-septicidal', 'Septicidal Capsule'), ('capsule-silique', 'Silique Capsule'), ('capsule-silicle', 'Silicle Capsule'), ('capsule-pyxis', 'Pyxis Capsule'), ('capsule-poricidal', 'Poricidal Capsule'), ('indehiscent', 'Indehiscent'), ('achene', 'Achene'), ('nut', 'Nut'), ('samara', 'Samara'), ('grain', 'Grain'), ('schizocarp', 'Schizocarp'), ('fleshy', 'Fleshy'), ('drupe', 'Drupe'), ('berry', 'Berry'), ('hesperidium', 'Hesperidium'), ('pepo', 'Pepo'), ('pome', 'Pome'), ('aggregate', 'Aggregate'), ('multiple', 'Multiple')], max_length=45), blank=True, null=True, size=None),
        ),
    ]
