# Generated by Django 2.2.10 on 2020-09-04 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20190812_1246'),
        ('life', '0013_auto_20191003_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonname',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commonNames', to='db.DocumentID'),
        ),
    ]
