# Generated by Django 2.2.13 on 2020-11-22 21:23

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0013_auto_20191003_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifenode',
            name='flower_colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('white', 'White'), ('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('pink', 'Pink'), ('lilac', 'Lilac'), ('blue', 'Blue'), ('light-blue', 'Light Blue'), ('green', 'Green'), ('purple', 'Purple'), ('black', 'Black'), ('brown', 'Brown'), ('nut-brown', 'Nut Brown'), ('wine', 'Wine'), ('cream', 'Cream')], max_length=25), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='lifenode',
            name='flower_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('inflorescence', 'Inflorescence'), ('pseudanthium', 'Composite Flower'), ('solitary', 'Solitary Flower')], max_length=45), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='lifenode',
            name='fruit_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('simple', 'Simple'), ('dry', 'Dry'), ('dehiscent', 'Dehiscent'), ('legume', 'Legume'), ('follicle', 'Follicle'), ('capsule', 'Capsule'), ('capsule-loculicidal', 'Loculicidal Capsule'), ('capsule-septicidal', 'Septicidal Capsule'), ('capsule-silique', 'Silique Capsule'), ('capsule-silicle', 'Silicle Capsule'), ('capsule-pyxis', 'Pyxis Capsule'), ('capsule-poricidal', 'Poricidal Capsule'), ('indehiscent', 'Indehiscent'), ('achene', 'Achene'), ('nut', 'Nut'), ('samara', 'Samara'), ('grain', 'Grain'), ('schizocarp', 'Schizocarp'), ('fleshy', 'Fleshy'), ('drupe', 'Drupe'), ('berry', 'Berry'), ('hesperidium', 'Hesperidium'), ('pepo', 'Pepo'), ('pome', 'Pome'), ('aggregate', 'Aggregate'), ('multiple', 'Multiple')], max_length=45), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='lifenode',
            name='growth_habit',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('herb', 'Herb'), ('graminoid', 'Graminoid'), ('lichenous', 'Lichenous'), ('nonvascular', 'Nonvascular'), ('succulent', 'Succulent'), ('shrub', 'Shrub'), ('subshrub', 'Subshrub'), ('tree', 'Tree'), ('vine', 'Vine')], max_length=25), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='lifenode',
            name='growth_rate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[('slow', 'Slow'), ('moderate', 'Moderate'), ('fast', 'Fast')]), null=True, size=None),
        ),
        migrations.AddField(
            model_name='lifenode',
            name='height',
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(null=True),
        ),
        migrations.AddField(
            model_name='lifenode',
            name='leaf_texture',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('cartacea', 'Cartácea'), ('membranacea', 'Membranácea'), ('herbacea', 'Herbácea'), ('coriaceas', 'Coríaceas'), ('succulent', 'Succulent')], max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='lifenode',
            name='leaf_type',
            field=models.CharField(blank=True, choices=[('simple', 'Simple'), ('compound', 'Compound'), ('spine', 'Spine')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='lifenode',
            name='phyllotaxy',
            field=models.CharField(blank=True, choices=[('opposite', 'Opposite'), ('opposite-distichous', 'Opposite Distichous'), ('alternate', 'Alternate'), ('alternate-spiral', 'Alternate Spiral'), ('alternate-distichous', 'Alternate Distichous'), ('whorl', 'Whorl'), ('rosette', 'Rosette')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='lifenode',
            name='spread',
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(null=True),
        ),
        migrations.AddField(
            model_name='lifenode',
            name='succession',
            field=models.IntegerField(choices=[(10, 'Primary'), (20, 'Secondary'), (30, 'Climax')], null=True),
        ),
        migrations.AddField(
            model_name='lifenode',
            name='sun',
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(null=True),
        ),
        migrations.AddField(
            model_name='lifenode',
            name='threatened',
            field=models.CharField(blank=True, choices=[('EX', 'Extinct'), ('EW', 'Extinct in the Wild'), ('CR', 'Critically Endangered'), ('EN', 'Endangered'), ('VU', 'Vulnerable'), ('NT', 'Near Threatened'), ('CD', 'Conservation Dependent'), ('LC', 'Least Concern'), ('DD', 'Data Deficient'), ('NE', 'Not Evaluated')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='lifenode',
            name='time_to_fruit',
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(null=True),
        ),
    ]
