# Generated by Django 2.2.4 on 2020-04-08 02:13

import db.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20190812_1246'),
        ('life', '0013_auto_20191003_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifenode',
            name='body_parts',
            field=db.fields.ManyToManyField(limit_choices_to=db.fields.limit_by_contenttype('life.BodyPart'), related_name='lifeNode_bodyPart', to='db.DocumentID'),
        ),
        migrations.CreateModel(
            name='BodyPartType',
            fields=[
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='+', serialize=False, to='db.Revision')),
                ('is_tip', models.NullBooleanField()),
                ('is_deleted', models.NullBooleanField()),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='db.DocumentID')),
            ],
            options={
                'ordering': ('document_id',),
                'abstract': False,
                'unique_together': {('is_tip', 'document')},
            },
            managers=[
                ('objects_revisions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='+', serialize=False, to='db.Revision')),
                ('is_tip', models.NullBooleanField()),
                ('is_deleted', models.NullBooleanField()),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=512)),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
                ('description', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='db.DocumentID')),
                ('images', db.fields.ManyToManyField(limit_choices_to=db.fields.limit_by_contenttype('images.Image'), related_name='bodyPart_image', to='db.DocumentID')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_bodyParts', to='db.DocumentID')),
                ('types', db.fields.ManyToManyField(limit_choices_to=db.fields.limit_by_contenttype('life.BodyPartType'), related_name='bodyPart_type', to='db.DocumentID')),
            ],
            options={
                'ordering': ('document_id',),
                'abstract': False,
                'unique_together': {('is_tip', 'document')},
            },
            managers=[
                ('objects_revisions', django.db.models.manager.Manager()),
            ],
        ),
    ]
