# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 21:37
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify


def forwards_func(apps, schema_editor):
    CommonName = apps.get_model("life", "CommonName")
    LifeNode = apps.get_model("life", "LifeNode")
    for name in CommonName.objects_revisions.all():
        lifeNode = LifeNode.objects_revisions.get(commonNames__id=name.pk)
        name.plant = lifeNode.document_id
        name.save_all_revisions(fields=['plant'])


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0014_commonname_plant'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
