# Generated by Django 2.2.13 on 2021-06-10 15:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0014_auto_20200408_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifenode',
            name='growth_rate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('slow', 'Slow'), ('moderate', 'Moderate'), ('fast', 'Fast')], max_length=25), blank=True, null=True, size=None),
        ),
    ]
