# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 21:37
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.utils.text import slugify


def forwards_func(apps, schema_editor):
    from life.models import CommonName, LifeNode
    for name in CommonName.objects_revisions.all():
        try:
            lifeNode = LifeNode.objects_revisions.get(commonNames__id=name.document_id)
            name.plant = lifeNode.document
            name.save(update_fields=['plant'], request=None)
        except LifeNode.MultipleObjectsReturned:
            lifeNodes = LifeNode.objects_revisions.filter(commonNames__id=name.document_id)

            name.plant = lifeNodes[0].document
            name.save(update_fields=['plant'], request=None)

            for lifeNode in lifeNodes[1:]:
                name_2 = CommonName(
                    name=name.name,
                    language=name.language,
                    country=name.country,
                    region=name.region,
                    plant=lifeNode.document
                )
                name_2.save(request=None)


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0014_commonname_plant'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
