# Generated by Django 2.2.24 on 2025-11-05 02:49

import db.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0011_auto_20190812_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sowing',
            fields=[
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='+', serialize=False, to='db.Revision')),
                ('is_tip', models.NullBooleanField()),
                ('is_deleted', models.NullBooleanField()),
                ('author_name', models.CharField(blank=True, max_length=128, null=True)),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
                ('where', models.CharField(blank=True, max_length=256, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sowing_author', to='db.DocumentID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='db.DocumentID')),
                ('images', db.fields.ManyToManyField(limit_choices_to=db.fields.limit_by_contenttype('images.Image'), related_name='sowing_image', to='db.DocumentID')),
                ('species', db.fields.ManyToManyField(limit_choices_to=db.fields.limit_by_contenttype('life.LifeNode'), related_name='sowing_species', to='db.DocumentID')),
            ],
            options={
                'ordering': ('document_id',),
                'abstract': False,
                'unique_together': {('is_tip', 'document')},
            },
            managers=[
                ('objects_revisions', django.db.models.manager.Manager()),
            ],
        ),
    ]
