# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0008_documentid_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='db.Revision')),
                ('is_tip', models.NullBooleanField()),
                ('is_deleted', models.NullBooleanField()),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('body', models.TextField()),
                ('published_at', models.DateTimeField(null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.DocumentID')),
            ],
            options={
                'ordering': ('-published_at',),
            },
            managers=[
                ('objects_revisions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('is_tip', 'url')]),
        ),
    ]
