# Generated by Django 2.2.4 on 2019-09-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0004_auto_20190812_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='is_request',
            field=models.BooleanField(default=False),
        ),
    ]
