# Generated by Django 2.2.13 on 2021-08-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0005_auto_20190914_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='is_cultivated',
        ),
        migrations.AddField(
            model_name='occurrence',
            name='canopy_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='canopy_position',
            field=models.CharField(blank=True, choices=[('emergent', 'Emergent'), ('canopy', 'Canopy'), ('sub-canopy', 'Sub-canopy'), ('sub-forest', 'Sub-forest'), ('isolated', 'Isolated')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='cbh',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Circumference at breast height', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='current_health_state',
            field=models.CharField(blank=True, choices=[('healthy', 'Healthy'), ('damaged', 'Damaged')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='current_health_state_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='dbh',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Diameter at breast height', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='local_population',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='regional_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='total_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='type',
            field=models.CharField(blank=True, choices=[('natural', 'Natural'), ('planted', 'Planted')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='type_of_trunk',
            field=models.CharField(blank=True, choices=[('straight', 'Straight'), ('bifurcated', 'Bifurcated'), ('crooked', 'Crooked')], max_length=25, null=True),
        ),
    ]
