# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=''),
        ),
    ]
