# Generated by Django 2.2.4 on 2019-08-12 12:46

from django.db import migrations, models
import django.db.models.deletion
import utils.upload


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_reputation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=utils.upload.set_upload_to_random_filename('accounts/avatar')),
        ),
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='db.DocumentID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='revision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='+', serialize=False, to='db.Revision'),
        ),
    ]
