# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
