# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_revision_author_useragent'),
        ('voting', '0002_auto_20160728_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='votes_author', to='db.DocumentID'),
            preserve_default=False,
        ),
    ]
