# Generated by Django 2.2.4 on 2019-08-12 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_vote_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ('document_id',)},
        ),
        migrations.AlterField(
            model_name='vote',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='db.DocumentID'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='revision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='+', serialize=False, to='db.Revision'),
        ),
    ]
