# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-21 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0008_documentid_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='db.Revision')),
                ('is_tip', models.NullBooleanField()),
                ('is_deleted', models.NullBooleanField()),
                ('image', models.ImageField(max_length=512, upload_to='')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.DocumentID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='db.DocumentID')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects_revisions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set([('is_tip', 'document')]),
        ),
    ]
