# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='subject',
        ),
    ]
