# Generated by Django 2.2.4 on 2019-08-12 12:46

from django.db import migrations, models
import django.db.models.deletion
import utils.upload


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('document_id',)},
        ),
        migrations.AlterField(
            model_name='image',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='db.DocumentID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=512, upload_to=utils.upload.set_upload_to_random_filename('images')),
        ),
        migrations.AlterField(
            model_name='image',
            name='revision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='+', serialize=False, to='db.Revision'),
        ),
    ]
