# Generated by Django 2.2.4 on 2019-10-05 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20190812_1246'),
        ('images', '0004_auto_20190812_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='db.DocumentID'),
        ),
    ]
