# Generated by Django 2.2.4 on 2020-04-15 01:53

import db.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0011_auto_20190812_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='+', serialize=False, to='db.Revision')),
                ('is_tip', models.NullBooleanField()),
                ('is_deleted', models.NullBooleanField()),
                ('types', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(3, 'Food'), (5, 'Ornamental'), (4, 'Medicinal'), (6, 'Wood'), (2, 'Dye'), (1, 'Energy'), (20, 'Other')]), size=None)),
                ('title', models.CharField(max_length=255)),
                ('source', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='db.DocumentID')),
                ('images', db.fields.ManyToManyField(limit_choices_to=db.fields.limit_by_contenttype('images.Image'), related_name='usage_image', to='db.DocumentID')),
                ('plants', db.fields.ManyToManyField(limit_choices_to=db.fields.limit_by_contenttype('life.Lifenode'), related_name='usage_plant', to='db.DocumentID')),
            ],
            options={
                'ordering': ('document_id',),
                'abstract': False,
                'unique_together': {('is_tip', 'document')},
            },
            managers=[
                ('objects_revisions', django.db.models.manager.Manager()),
            ],
        ),
    ]
