# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-24 23:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0009_documentid_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='+', serialize=False, to='db.Revision')),
                ('is_tip', models.NullBooleanField()),
                ('is_deleted', models.NullBooleanField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('url', models.SlugField(max_length=255)),
                ('items', django.contrib.postgres.fields.jsonb.JSONField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='db.DocumentID')),
            ],
            options={
                'ordering': ('document_id',),
                'abstract': False,
            },
            managers=[
                ('objects_revisions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='list',
            unique_together=set([('is_tip', 'document')]),
        ),
    ]
