# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-24 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
