# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-24 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20170224_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
