# Generated by Django 2.2.4 on 2019-11-19 00:00

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20190812_1246'),
        ('lists', '0004_auto_20170224_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishItem',
            fields=[
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='+', serialize=False, to='db.Revision')),
                ('is_tip', models.NullBooleanField()),
                ('is_deleted', models.NullBooleanField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='db.DocumentID')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wish_item_plant', to='db.DocumentID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_item_user', to='db.DocumentID')),
            ],
            options={
                'ordering': ('document_id',),
                'abstract': False,
                'unique_together': {('is_tip', 'document')},
            },
            managers=[
                ('objects_revisions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='+', serialize=False, to='db.Revision')),
                ('is_tip', models.NullBooleanField()),
                ('is_deleted', models.NullBooleanField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='db.DocumentID')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_item_plant', to='db.DocumentID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_item_user', to='db.DocumentID')),
            ],
            options={
                'ordering': ('document_id',),
                'abstract': False,
                'unique_together': {('is_tip', 'document')},
            },
            managers=[
                ('objects_revisions', django.db.models.manager.Manager()),
            ],
        ),
    ]
