# Generated by Django 2.2.13 on 2020-10-14 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20190812_1246'),
        ('lists', '0005_collectionitem_wishitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('collection_count', models.IntegerField(default=0)),
                ('wish_count', models.IntegerField(default=0)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.DocumentID')),
            ],
        ),
    ]
