# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-21 15:27
from __future__ import unicode_literals

import db.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0008_documentid_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionID',
            fields=[
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='db.Revision')),
                ('is_tip', models.NullBooleanField()),
                ('is_deleted', models.NullBooleanField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_author', to='db.DocumentID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.DocumentID')),
                ('identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_life', to='db.DocumentID')),
                ('whatisthis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_whatisthis', to='db.DocumentID')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects_revisions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WhatIsThis',
            fields=[
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='db.Revision')),
                ('is_tip', models.NullBooleanField()),
                ('is_deleted', models.NullBooleanField()),
                ('when', models.CharField(blank=True, max_length=256, null=True)),
                ('where', models.CharField(blank=True, max_length=256, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatisthis_author', to='db.DocumentID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.DocumentID')),
                ('images', db.fields.ManyToManyField(related_name='whatisthis_image', to='db.DocumentID')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatisthis_subject', to='db.DocumentID')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects_revisions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='whatisthis',
            unique_together=set([('is_tip', 'document')]),
        ),
        migrations.AlterUniqueTogether(
            name='suggestionid',
            unique_together=set([('is_tip', 'document')]),
        ),
    ]
