# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_documentid_owner'),
        ('what', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestionid',
            options={'ordering': ('document_id',)},
        ),
        migrations.AlterModelOptions(
            name='whatisthis',
            options={'ordering': ('document_id',)},
        ),
        migrations.AddField(
            model_name='suggestionid',
            name='is_correct',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='whatisthis',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatisthis_answer', to='db.DocumentID'),
        ),
    ]
