# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-10 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('what', '0002_auto_20161128_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestionid',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestionid_author', to='db.DocumentID'),
        ),
        migrations.AlterField(
            model_name='suggestionid',
            name='identification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestionid_life', to='db.DocumentID'),
        ),
        migrations.AlterField(
            model_name='suggestionid',
            name='whatisthis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestionid_whatisthis', to='db.DocumentID'),
        ),
    ]
